name: Arsenius's development blog
description: Finding new ways to blow up my laptop
meta_description: "Finding new ways to blow up my laptop"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://dev.arseniuss.id.lv"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://dev.arseniuss.id.lv"
author: "Armands Arseniuss Skolmeisters"

# Disqus config
disqus-shortname: "dev-arseniuss-id-lv"
